# Full project: https://gitlab.com/pages/doxygen
image: ubuntu:trusty

pages:
  script:
    - export DEBIAN_FRONTEND=noninteractive
    - apt-get -yq update
    - apt-get -yq install graphviz
    - apt-get -yq install doxygen
    - doxygen doxygen/Doxyfile
    - mv documentation/html/ public/
  artifacts:
    paths:
      - public
  only:
    - master
